### ISSUE TITLE
Feature request: Add option to decouple lightness and saturation sliders

### ISSUE THREAD

**Issue by brybrant** [KraXen72/bismuth#2]
Hi, this addon is great, but I really need to be able to adjust hue, saturation, and lightness independently - could you perhaps add a toggle button to switch between this behaviour and the existing behaviour?

Adjusting saturation and lightness seperately yields a diagonal movement across a color gradient, instead of just X and Y movement like your addon.
([this website is a good example](https://hslpicker.com))

As a bonus, I would also love to see a table of 'saved colors' so I can play with the sliders, then click on a save button to have that color saved to the table (and a way to remove colors from my saved table). Then when I hover over each saved color, a tooltip shows me information about the color like the HEX, RGB, HSL, CMYK.

Thanks!

**Comment by KraXen72** [comment]
you can change the numbers in the hsl inputs and it updates the colors. might add scroll support to the inputs, so you could adjust them by scrolling.

saved colors are planned.
as i said in the other issue, no ETA since i'm pretty busy. feel free to open a PR with these features if you want to. if not i'll add it eventually.

**Comment by KraXen72** [comment]
i added scroll support for input boxes, but i haven't released a new firefox extension version yet. if you use firefox, let me know and i'll release it.
